### ISSUE TITLE
Windows RegEx Support

### ISSUE THREAD

**Issue by jasonkolodziej** [docsbydoxdox/doxdox#91]
Sorry the **'******'** are actual directories. But there seems to be some issues with Windows 10, could someone help.

```
const REPLACE_FILENAME_REGEXP = new RegExp(`^(${process.cwd()}/|./)`, 'u');
                                ^

SyntaxError: Invalid regular expression: /^(C:\Users\****\Documents\****\*****\folder1/|./)/: Invalid escape
    at new RegExp (<anonymous>)
    at Object.<anonymous> (C:\Users\*****\AppData\Roaming\npm\node_modules\doxdox\lib\doxdox.js:18:33)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\*****\AppData\Roaming\npm\node_modules\doxdox\bin\doxdox:9:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by nrgapple** [comment]
Same issue. Is this repo no longer maintained?

**Comment by neogeek** [comment]
The way paths are handled in the latest version (v4.0.0-preview.2), this should no longer be an issue.
